#KubeJS Common Properties
#Tue Mar 10 23:44:25 JST 2026
matchJsonRecipes=true
allowAsyncStreams=true
announceReload=true
startupErrorGUI=true
serverOnly=false
hideServerScriptErrors=false
saveDevPropertiesInConfig=false
packmode=
ignoreCustomUniqueRecipeIds=false
creativeModeTabIcon=kubejs\:gear_mechanism
startupErrorReportUrl=
