name = "Create-Astralization"
author = "gha"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2696cb31cd4f1949bb16ecb942a5d626d17e4d52c338ba84477f162dbc6b4143"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
