name = "Create-Astralization"
author = "gha"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4159074fa7ed45ac40ee672bd7cea4f53f9700b8f80342cddedae558e2778ac8"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
