// タグ関係

ServerEvents.tags('block', e => {
  // AdAstraのタグ
  e.add('ad_astra:destroyed_in_space', '#chipped:torch')
  e.add('ad_astra:destroyed_in_space', '#chipped:lantern')
  e.add('ad_astra:destroyed_in_space', '#chipped:jack_o_lantern')
  e.add('ad_astra:destroyed_in_space', '#chipped:vine')
  e.add('ad_astra:destroyed_in_space', '#chipped:brown_mushroom_block')
  e.add('ad_astra:destroyed_in_space', '#chipped:red_mushroom_block')
  e.add('ad_astra:destroyed_in_space', 'supplementaries:sconce')
  e.add('ad_astra:destroyed_in_space', '#supplementaries:candle_holders')
  e.add('ad_astra:destroyed_in_space', 'farmersdelight:sandy_shrub')

  // 硬化した凍てつく灰になる
  e.add('kubejs:transform_to_hardened_frigid_ash', 'ad_astra:moon_stone')
  e.add('kubejs:transform_to_hardened_frigid_ash', 'ad_astra:mars_stone')
  e.add('kubejs:transform_to_hardened_frigid_ash', 'ad_astra:venus_stone')
  e.add('kubejs:transform_to_hardened_frigid_ash', 'ad_astra:mercury_stone')
  e.add('kubejs:transform_to_hardened_frigid_ash', 'ad_astra:glacio_stone')
  e.add('kubejs:transform_to_hardened_frigid_ash', 'ad_astra:moon_cobblestone')
  e.add('kubejs:transform_to_hardened_frigid_ash', 'ad_astra:mars_cobblestone')
  e.add('kubejs:transform_to_hardened_frigid_ash', 'ad_astra:venus_cobblestone')
  e.add('kubejs:transform_to_hardened_frigid_ash', 'ad_astra:mercury_cobblestone')
  e.add('kubejs:transform_to_hardened_frigid_ash', 'ad_astra:glacio_cobblestone')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#stone_tool_materials')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#c:sandstone_blocks')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#c:ores')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#forge:stone')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#forge:cobblestone')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#create:stone_types/granite')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#create:stone_types/diorite')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#create:stone_types/andesite')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#create:stone_types/deepslate')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#create:stone_types/dripstone')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#create:stone_types/tuff')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#create:stone_types/asurine')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#create:stone_types/crimsite')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#create:stone_types/ochrum')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#create:stone_types/calcite')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#create:stone_types/scoria')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#create:stone_types/limestone')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#create:stone_types/scorchia')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#create:stone_types/veridium')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#vintage:stone_types/basalt')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#createnuclear:stone_types/autunite')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#tfmg:stone_types/bauxite')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#tfmg:stone_types/galena')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:cobblestone')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:mossy_cobblestone')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:granite')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:diorite')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:andesite')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:deepslate')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:calcite')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:dripstone_block')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:tuff')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:end_stone')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:sandstone')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:red_sandstone')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:blackstone')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:pointed_dripstone')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:glowstone')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:amethyst_block')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:borderless_bricks')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:bricks')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:prismarine')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:dark_prismarine')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:crying_obsidian')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:lodestone')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:glided_blackstone')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:magma_block')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:netherrack')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:nether_bricks')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:red_nether_bricks')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:obsidian')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:stone')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#chipped:smooth_stone')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#create_chipped:asurine')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#create_chipped:crimsite')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#create_chipped:ochrum')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#create_chipped:scoria')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#create_chipped:limestone')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#create_chipped:scorchia')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#create_chipped:veridium')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#rechiseled:andesite')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#rechiseled:granite')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#rechiseled:diorite')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#rechiseled:stone')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#rechiseled:basalt')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#rechiseled:blackstone')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#rechiseled:amethyst_block')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#rechiseled:prismarine_bricks')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#rechiseled:dark_prismarine')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#rechiseled:deepslate')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#rechiseled:cobbled_deepslate')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#rechiseled:cobblestone')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#rechiseled:nether_bricks')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#rechiseled:obsidian')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#rechiseled:purpur_block')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#rechiseled:quartz_block')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#rechiseled:red_nether_bricks')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#rechiseled:sandstone')
  e.add('kubejs:transform_to_hardened_frigid_ash', '#rechiseled:red_sandstone')

  // 凍てつく灰
  e.add('kubejs:frigid_ash', 'kubejs:frigid_ash')
  e.add('kubejs:frigid_ash', 'kubejs:hardened_frigid_ash')
})

ServerEvents.tags('item', e => {

  // AdAstraのタグ
  e.add('ad_astra:destroyed_in_space', '#chipped:torch')
  e.add('ad_astra:destroyed_in_space', '#chipped:lantern')
  e.add('ad_astra:destroyed_in_space', '#chipped:jack_o_lantern')
  e.add('ad_astra:destroyed_in_space', '#chipped:vine')
  e.add('ad_astra:destroyed_in_space', '#chipped:brown_mushroom_block')
  e.add('ad_astra:destroyed_in_space', '#chipped:red_mushroom_block')
  e.add('ad_astra:destroyed_in_space', 'supplementaries:sconce')
  e.add('ad_astra:destroyed_in_space', '#supplementaries:candle_holders')
  e.add('ad_astra:destroyed_in_space', 'farmersdelight:sandy_shrub')

  // 貨物ロケット不可
  e.add('ad_astra_cargo_rockets:denied_in_launch_pad', 'supplementaries:sack')
  e.add('ad_astra_cargo_rockets:denied_in_launch_pad', 'supplementaries:safe')
  e.add('ad_astra_cargo_rockets:denied_in_launch_pad', 'sophisticatedbackpacks:backpack')
  e.add('ad_astra_cargo_rockets:denied_in_launch_pad', 'sophisticatedbackpacks:copper_backpack')
  e.add('ad_astra_cargo_rockets:denied_in_launch_pad', 'sophisticatedbackpacks:iron_backpack')
  e.add('ad_astra_cargo_rockets:denied_in_launch_pad', 'sophisticatedbackpacks:gold_backpack')
  e.add('ad_astra_cargo_rockets:denied_in_launch_pad', 'sophisticatedbackpacks:diamond_backpack')
  e.add('ad_astra_cargo_rockets:denied_in_launch_pad', 'sophisticatedbackpacks:netherite_backpack')
  e.add('ad_astra_cargo_rockets:denied_in_launch_pad', 'create:minecart_contraption')
  e.add('ad_astra_cargo_rockets:denied_in_launch_pad', 'create:furnace_minecart_contraption')
  e.add('ad_astra_cargo_rockets:denied_in_launch_pad', 'create:chest_minecart_contraption')

  // シュルカーボックス不可
  e.add('supplementaries:shulker_blacklist', 'sophisticatedbackpacks:backpack')
  e.add('supplementaries:shulker_blacklist', 'sophisticatedbackpacks:copper_backpack')
  e.add('supplementaries:shulker_blacklist', 'sophisticatedbackpacks:iron_backpack')
  e.add('supplementaries:shulker_blacklist', 'sophisticatedbackpacks:gold_backpack')
  e.add('supplementaries:shulker_blacklist', 'sophisticatedbackpacks:diamond_backpack')
  e.add('supplementaries:shulker_blacklist', 'sophisticatedbackpacks:netherite_backpack')
  e.add('supplementaries:shulker_blacklist', 'kubejs:glacite')
  e.add('supplementaries:shulker_blacklist', 'kubejs:unfinished_exquisite_glacite')
  e.add('supplementaries:shulker_blacklist', 'kubejs:exquisite_glacite')
  e.add('supplementaries:shulker_blacklist', 'kubejs:zerothium_ingot')
  e.add('supplementaries:shulker_blacklist', 'create:minecart_contraption')
  e.add('supplementaries:shulker_blacklist', 'create:furnace_minecart_contraption')
  e.add('supplementaries:shulker_blacklist', 'create:chest_minecart_contraption')

  // タグがない金属アイテムの修正
  e.add('forge:nuggets/netherite', 'createdeco:netherite_nugget')
  e.add('forge:nuggets', 'createdeco:netherite_nugget')
  e.add('c:nuggets', 'createdeco:netherite_nugget')

  e.add('forge:plates/andesite', 'createdeco:andesite_sheet')
  e.add('forge:plates', 'createdeco:andesite_sheet')
  e.add('c:plates', 'createdeco:andesite_sheet')

  e.add('forge:ingots/industrial_iron', 'createdeco:industrial_iron_ingot')
  e.add('forge:ingots', 'createdeco:industrial_iron_ingot')
  e.add('c:ingots', 'createdeco:industrial_iron_ingot')

  e.add('forge:plates/industrial_iron', 'createdeco:industrial_iron_sheet')
  e.add('forge:plates', 'createdeco:industrial_iron_sheet')
  e.add('c:plates', 'createdeco:industrial_iron_sheet')

  e.add('forge:nuggets/industrial_iron', 'createdeco:industrial_iron_nugget')
  e.add('forge:nuggets', 'createdeco:industrial_iron_nugget')
  e.add('c:nuggets', 'createdeco:industrial_iron_nugget')

  e.add('createdeco:internal/plates/zinc_plates', 'createaddition:zinc_sheet')

  // Silentgear
  e.add('silentgear:starlight_charger_catalysts/tier1', 'blaze_powder')
  e.add('silentgear:starlight_charger_catalysts/tier2', 'silentgear:azure_silver_ingot')

  // 粉
  e.add('c:dusts', 'sugar')
  e.add('c:dusts', 'tfmg:bauxite_powder')
  e.add('c:dusts', 'tfmg:thermite_powder')
  e.add('c:dusts', 'gunpowder')
  e.add('c:dusts', 'blaze_powder')
  e.add('c:dusts', 'silentgear:glowing_dust')
  e.add('c:dusts', 'silentgear:blazing_dust')
  e.add('c:dusts', 'silentgear:glittery_dust')
  e.add('c:dusts', 'tfmg:nitrate_dust')
  e.add('forge:dusts', 'sugar')
  e.add('forge:dusts', 'tfmg:bauxite_powder')
  e.add('forge:dusts', 'tfmg:thermite_powder')
  e.add('forge:dusts', 'gunpowder')
  e.add('forge:dusts', 'blaze_powder')
  e.add('forge:dusts', 'silentgear:glowing_dust')
  e.add('forge:dusts', 'silentgear:blazing_dust')
  e.add('forge:dusts', 'silentgear:glittery_dust')
  e.add('forge:dusts', 'tfmg:nitrate_dust')

  // EMIから非表示
  e.add('c:hidden_from_recipe_viewers', 'vintage:sulfuric_acid_bucket')
})

ServerEvents.tags('fluid', e => {

  // EMIから非表示
  e.add('c:hidden_from_recipe_viewers', 'vintage:sulfur_dioxide')
  e.add('c:hidden_from_recipe_viewers', 'vintage:sulfur_trioxide')
  e.add('c:hidden_from_recipe_viewers', 'vintage:sulfuric_acid')
})