
["Jetpack Height Restriction"]
	brassJetpackMaxHeight = 28.0
	andesiteJetpackMaxHeight = 18.0
	copperJetpackMaxHeight = 12.0
	netheriteJetpackMaxHeight = 48.0
	enableAboveCloudEnchant = false

["Jetpack/Grapplin Speed"]
	brassJetpackSpeed = 0.02
	andesiteJetpackSpeed = 0.015
	copperJetpackSpeed = 0.01
	netheriteJetpackSpeed = 0.03
	grapplinWhiskSpeed = 0.2

["Fuel/Water Capacity"]
	gadgetCapacity = 1600.0
	smallTankCapacity = 800.0
	mediumTankCapacity = 1600.0
	largeTankCapacity = 3200.0

[Enchantments]
	enableDiggingEnchant = true
	enableImpactEnchant = true
	enableGravityGunEnchant = false
	enableHellfireEnchant = true
	enableChunkEaterEnchant = true

["Drone Module"]
	enableDrillDroneModule = true
	enableFanDroneModule = true
	enableMagnetDroneModule = true
	enableVaultDroneModule = true
	MagnetModuleBlockLimitation = false

